from enum import Enum


class DESFireKeyType(Enum):
    DF_KEY_2K3DES = 0x00  # for DFEV1_INS_AUTHENTICATE_ISO + DF_INS_AUTHENTICATE_LEGACY
    DF_KEY_3K3DES = 0x40  # for DFEV1_INS_AUTHENTICATE_ISO
    DF_KEY_AES = 0x80  # for DFEV1_INS_AUTHENTICATE_AES
    DF_KEY_INVALID = 0xFF
